eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

okta:
  oauth2:
    issuer: https://dev-25136160.okta.com/oauth2/default
    audience: api://default
